/*
 * Copyright 2018 Skynav, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY SKYNAV, INC. AND ITS CONTRIBUTORS “AS IS” AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL SKYNAV, INC. OR ITS CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package com.skynav.ttv.model.ttml;

import java.net.URI;

import com.skynav.ttv.model.Profile.Usage;

import static com.skynav.ttv.model.ttml.TTML2.Constants.*;

public class TTML2FullProfileSpecification extends TTML1FullProfileSpecification {

    private static final Object[][] featureMapEntries = new Object[][] {
        { "#animate", Usage.REQUIRED },
        { "#animate-fill", Usage.REQUIRED },
        { "#animate-minimal", Usage.REQUIRED },
        { "#animate-paced", Usage.REQUIRED },
        { "#animate-spline", Usage.REQUIRED },
        { "#animate-repeat", Usage.REQUIRED },
        { "#animation", Usage.REQUIRED },
        { "#animation-out-of-line", Usage.REQUIRED },
        { "#animation-version-2", Usage.REQUIRED },
        { "#audio", Usage.REQUIRED },
        { "#audio-description", Usage.REQUIRED },
        { "#audio-speech", Usage.REQUIRED },
        { "#background", Usage.REQUIRED },
        { "#background-image", Usage.REQUIRED },
        { "#backgroundClip", Usage.REQUIRED },
        { "#backgroundColor-block", Usage.REQUIRED },
        { "#backgroundColor-inline", Usage.REQUIRED },
        { "#backgroundColor-region", Usage.REQUIRED },
        { "#backgroundColor", Usage.REQUIRED },
        { "#backgroundExtent", Usage.REQUIRED },
        { "#backgroundImage", Usage.REQUIRED },
        { "#backgroundOrigin", Usage.REQUIRED },
        { "#backgroundPosition", Usage.REQUIRED },
        { "#backgroundRepeat", Usage.REQUIRED },
        { "#base", Usage.REQUIRED },
        { "#base-general", Usage.REQUIRED },
        { "#base-version-2", Usage.REQUIRED },
        { "#bidi", Usage.REQUIRED },
        { "#bidi-version-2", Usage.REQUIRED },
        { "#border", Usage.REQUIRED },
        { "#border-block", Usage.REQUIRED },
        { "#border-inline", Usage.REQUIRED },
        { "#border-radii", Usage.REQUIRED },
        { "#border-radii-1", Usage.REQUIRED },
        { "#border-radii-2", Usage.REQUIRED },
        { "#border-region", Usage.REQUIRED },
        { "#bpd", Usage.REQUIRED },
        { "#cellResolution", Usage.REQUIRED },
        { "#chunk", Usage.REQUIRED },
        { "#clockMode", Usage.REQUIRED },
        { "#clockMode-gps", Usage.REQUIRED },
        { "#clockMode-local", Usage.REQUIRED },
        { "#clockMode-utc", Usage.REQUIRED },
        { "#color", Usage.REQUIRED },
        { "#condition", Usage.REQUIRED },
        { "#condition-fn-media", Usage.REQUIRED },
        { "#condition-fn-parameter", Usage.REQUIRED },
        { "#condition-fn-supports", Usage.REQUIRED },
        { "#condition-primary", Usage.REQUIRED },
        { "#content", Usage.REQUIRED },
        { "#content-sizing", Usage.REQUIRED },
        { "#contentProfiles", Usage.REQUIRED },
        { "#contentProfiles-combined", Usage.REQUIRED },
        { "#core", Usage.REQUIRED },
        { "#data", Usage.REQUIRED },
        { "#direction", Usage.REQUIRED },
        { "#disparity", Usage.REQUIRED },
        { "#display", Usage.REQUIRED },
        { "#display-block", Usage.REQUIRED },
        { "#display-inline", Usage.REQUIRED },
        { "#display-inlineBlock", Usage.REQUIRED },
        { "#display-region", Usage.REQUIRED },
        { "#display-version-2", Usage.REQUIRED },
        { "#displayAlign", Usage.REQUIRED },
        { "#displayAlign-block", Usage.REQUIRED },
        { "#displayAlign-justify", Usage.REQUIRED },
        { "#displayAlign-region", Usage.REQUIRED },
        { "#displayAlign-relative", Usage.REQUIRED },
        { "#displayAlign-version-2", Usage.REQUIRED },
        { "#displayAspectRatio", Usage.REQUIRED },
        { "#dropMode", Usage.REQUIRED },
        { "#dropMode-dropNTSC", Usage.REQUIRED },
        { "#dropMode-dropPAL", Usage.REQUIRED },
        { "#dropMode-nonDrop", Usage.REQUIRED },
        { "#embedded-audio", Usage.REQUIRED },
        { "#embedded-content", Usage.REQUIRED },
        { "#embedded-data", Usage.REQUIRED },
        { "#embedded-font", Usage.REQUIRED },
        { "#embedded-image", Usage.REQUIRED },
        { "#extent", Usage.REQUIRED },
        { "#extent-auto", Usage.REQUIRED },
        { "#extent-auto-version-2", Usage.REQUIRED },
        { "#extent-contain", Usage.REQUIRED },
        { "#extent-cover", Usage.REQUIRED },
        { "#extent-full-version-2", Usage.REQUIRED },
        { "#extent-image", Usage.REQUIRED },
        { "#extent-length", Usage.REQUIRED },
        { "#extent-length-version-2", Usage.REQUIRED },
        { "#extent-measure", Usage.REQUIRED },
        { "#extent-region", Usage.REQUIRED },
        { "#extent-region-version-2", Usage.REQUIRED },
        { "#extent-root", Usage.REQUIRED },
        { "#extent-root-version-2", Usage.REQUIRED },
        { "#extent-version-2", Usage.REQUIRED },
        { "#font", Usage.REQUIRED },
        { "#fontFamily", Usage.REQUIRED },
        { "#fontFamily-generic", Usage.REQUIRED },
        { "#fontFamily-non-generic", Usage.REQUIRED },
        { "#fontKerning", Usage.REQUIRED },
        { "#fontSelectionStrategy", Usage.REQUIRED },
        { "#fontSelectionStrategy-character", Usage.REQUIRED },
        { "#fontShear", Usage.REQUIRED },
        { "#fontSize", Usage.REQUIRED },
        { "#fontSize-anamorphic", Usage.REQUIRED },
        { "#fontSize-isomorphic", Usage.REQUIRED },
        { "#fontStyle", Usage.REQUIRED },
        { "#fontStyle-italic", Usage.REQUIRED },
        { "#fontStyle-oblique", Usage.REQUIRED },
        { "#fontVariant", Usage.REQUIRED },
        { "#fontWeight", Usage.REQUIRED },
        { "#fontWeight-bold", Usage.REQUIRED },
        { "#frameRate", Usage.REQUIRED },
        { "#frameRateMultiplier", Usage.REQUIRED },
        { "#gain", Usage.REQUIRED },
        { "#image", Usage.REQUIRED },
        { "#image-png", Usage.REQUIRED },
        { "#initial", Usage.REQUIRED },
        { "#ipd", Usage.REQUIRED },
        { "#layout", Usage.REQUIRED },
        { "#length", Usage.REQUIRED },
        { "#length-cell", Usage.REQUIRED },
        { "#length-em", Usage.REQUIRED },
        { "#length-integer", Usage.REQUIRED },
        { "#length-negative", Usage.REQUIRED },
        { "#length-percentage", Usage.REQUIRED },
        { "#length-pixel", Usage.REQUIRED },
        { "#length-positive", Usage.REQUIRED },
        { "#length-real", Usage.REQUIRED },
        { "#length-root-container-relative", Usage.REQUIRED },
        { "#length-version-2", Usage.REQUIRED },
        { "#letterSpacing", Usage.REQUIRED },
        { "#lineBreak-uax14", Usage.REQUIRED },
        { "#lineHeight", Usage.REQUIRED },
        { "#lineShear", Usage.REQUIRED },
        { "#luminance", Usage.REQUIRED },
        { "#markerMode", Usage.REQUIRED },
        { "#markerMode-continuous", Usage.REQUIRED },
        { "#markerMode-discontinuous", Usage.REQUIRED },
        { "#metadata", Usage.REQUIRED },
        { "#metadata-item", Usage.REQUIRED },
        { "#metadata-version-2", Usage.REQUIRED },
        { "#nested-div", Usage.REQUIRED },
        { "#nested-span", Usage.REQUIRED },
        { "#opacity", Usage.REQUIRED },
        { "#opacity-block", Usage.REQUIRED },
        { "#opacity-inline", Usage.REQUIRED },
        { "#opacity-region", Usage.REQUIRED },
        { "#opacity-version-2", Usage.REQUIRED },
        { "#origin", Usage.REQUIRED },
        { "#overflow", Usage.REQUIRED },
        { "#overflow-visible", Usage.REQUIRED },
        { "#padding", Usage.REQUIRED },
        { "#padding-1", Usage.REQUIRED },
        { "#padding-2", Usage.REQUIRED },
        { "#padding-3", Usage.REQUIRED },
        { "#padding-4", Usage.REQUIRED },
        { "#padding-block", Usage.REQUIRED },
        { "#padding-inline", Usage.REQUIRED },
        { "#padding-region", Usage.REQUIRED },
        { "#padding-version-2", Usage.REQUIRED },
        { "#pan", Usage.REQUIRED },
        { "#permitFeatureNarrowing", Usage.REQUIRED },
        { "#permitFeatureWidening", Usage.REQUIRED },
        { "#pitch", Usage.REQUIRED },
        { "#pixelAspectRatio", Usage.REQUIRED },
        { "#position", Usage.REQUIRED },
        { "#presentation", Usage.REQUIRED },
        { "#presentation-version-2", Usage.REQUIRED },
        { "#processorProfiles", Usage.REQUIRED },
        { "#processorProfiles-combined", Usage.REQUIRED },
        { "#profile", Usage.REQUIRED },
        { "#profile-full-version-2", Usage.REQUIRED },
        { "#profile-nesting", Usage.REQUIRED },
        { "#profile-version-2", Usage.REQUIRED },
        { "#region-implied-animation", Usage.REQUIRED },
        { "#region-inline", Usage.REQUIRED },
        { "#region-timing", Usage.REQUIRED },
        { "#resources", Usage.REQUIRED },
        { "#ruby", Usage.REQUIRED },
        { "#ruby-full", Usage.REQUIRED },
        { "#rubyAlign", Usage.REQUIRED },
        { "#rubyAlign-minimal", Usage.REQUIRED },
        { "#rubyAlign-withBase", Usage.REQUIRED },
        { "#rubyPosition", Usage.REQUIRED },
        { "#rubyReserve", Usage.REQUIRED },
        { "#set", Usage.REQUIRED },
        { "#set-fill", Usage.REQUIRED },
        { "#set-multiple-styles", Usage.REQUIRED },
        { "#set-repeat", Usage.REQUIRED },
        { "#shear", Usage.REQUIRED },
        { "#showBackground", Usage.REQUIRED },
        { "#source", Usage.REQUIRED },
        { "#speak", Usage.REQUIRED },
        { "#speech", Usage.REQUIRED },
        { "#structure", Usage.REQUIRED },
        { "#styling", Usage.REQUIRED },
        { "#styling-chained", Usage.REQUIRED },
        { "#styling-inheritance-content", Usage.REQUIRED },
        { "#styling-inheritance-region", Usage.REQUIRED },
        { "#styling-inline", Usage.REQUIRED },
        { "#styling-nested", Usage.REQUIRED },
        { "#styling-referential", Usage.REQUIRED },
        { "#subFrameRate", Usage.REQUIRED },
        { "#textAlign", Usage.REQUIRED },
        { "#textAlign-absolute", Usage.REQUIRED },
        { "#textAlign-justify", Usage.REQUIRED },
        { "#textAlign-relative", Usage.REQUIRED },
        { "#textAlign-version-2", Usage.REQUIRED },
        { "#textCombine", Usage.REQUIRED },
        { "#textDecoration", Usage.REQUIRED },
        { "#textDecoration-over", Usage.REQUIRED },
        { "#textDecoration-through", Usage.REQUIRED },
        { "#textDecoration-under", Usage.REQUIRED },
        { "#textEmphasis", Usage.REQUIRED },
        { "#textEmphasis-color", Usage.REQUIRED },
        { "#textEmphasis-minimal", Usage.REQUIRED },
        { "#textEmphasis-quoted-string", Usage.REQUIRED },
        { "#textOrientation", Usage.REQUIRED },
        { "#textOrientation-sideways-LR", Usage.REQUIRED },
        { "#textOutline", Usage.REQUIRED },
        { "#textOutline-blurred", Usage.REQUIRED },
        { "#textOutline-unblurred", Usage.REQUIRED },
        { "#textShadow", Usage.REQUIRED },
        { "#tickRate", Usage.REQUIRED },
        { "#time-clock-with-frames", Usage.REQUIRED },
        { "#time-clock", Usage.REQUIRED },
        { "#time-offset-with-frames", Usage.REQUIRED },
        { "#time-offset-with-ticks", Usage.REQUIRED },
        { "#time-offset", Usage.REQUIRED },
        { "#time-wall-clock", Usage.REQUIRED },
        { "#timeBase-clock", Usage.REQUIRED },
        { "#timeBase-media", Usage.REQUIRED },
        { "#timeBase-smpte", Usage.REQUIRED },
        { "#timeContainer", Usage.REQUIRED },
        { "#timing", Usage.REQUIRED },
        { "#transformation", Usage.REQUIRED },
        { "#transformation-version-2", Usage.REQUIRED },
        { "#unicodeBidi", Usage.REQUIRED },
        { "#unicodeBidi-isolate", Usage.REQUIRED },
        { "#unicodeBidi-version-2", Usage.REQUIRED },
        { "#validation", Usage.REQUIRED },
        { "#visibility", Usage.REQUIRED },
        { "#visibility-block", Usage.REQUIRED },
        { "#visibility-image", Usage.REQUIRED },
        { "#visibility-inline", Usage.REQUIRED },
        { "#visibility-region", Usage.REQUIRED },
        { "#visibility-version-2", Usage.REQUIRED },
        { "#wrapOption", Usage.REQUIRED },
        { "#writingMode", Usage.REQUIRED },
        { "#writingMode-horizontal-lr", Usage.REQUIRED },
        { "#writingMode-horizontal-rl", Usage.REQUIRED },
        { "#writingMode-horizontal", Usage.REQUIRED },
        { "#writingMode-vertical", Usage.REQUIRED },
        { "#xlink", Usage.REQUIRED },
        { "#zIndex", Usage.REQUIRED }
    };

    private static final Object[][] extensionMapEntries = new Object[][] {
    };

    public TTML2FullProfileSpecification(URI profileUri) {
        super(profileUri, null, featuresMap(NAMESPACE_TT_FEATURE, featureMapEntries), extensionsMap(NAMESPACE_TT_EXTENSION, extensionMapEntries));
    }

}
